### ISSUE TITLE
firebase.firestore().settings() is missing

### ISSUE THREAD

**Issue by BrianChapman** [EddyVerbruggen/nativescript-plugin-firebase#1036]
The settings method on firebase.firestore.Firestore appears to be missing. How do you set the settings for the firestore (example: timestampsInSnapshots: true)?

https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#settings

**Comment by EddyVerbruggen** [comment]
I looked at the web API and it seems like the only relevant options are `persist` and `timestampsInSnapshots`. You can use `persist` during `init`, and `timestampsInSnapshots` has been enabled by the plugin on iOS for a few versions (because of deprecation warnings). I've also enabled it for Android with 7.4.3.

Would you need to be able to configure `timestampsInSnapshots` from your app's code (so be able to set it to `false`)? If not, I think I won't expose a property.

**Comment by BrianChapman** [comment]
Got it, I didn't notice the deprecation warning.

**Comment by canhkieu** [comment]
I used version:     "nativescript-plugin-firebase": "^7.6.0"
And I got this error because I can not settings

```
const firestore = firebase.firestore()
// const settings = { /* your settings... */ timestampsInSnapshots: true }
// firestore.settings(settings) => If I enable this line, It's display Error: settings is not function
```

```
FirebaseFirestore has already been started and its settings can no longer be changed. You can only
call setFirestoreSettings() before calling any other methods on a FirebaseFirestore object.
```
