### ISSUE TITLE
Is there some way to re-auth with Google Login

### ISSUE THREAD

**Issue by calebeaires** [EddyVerbruggen/nativescript-plugin-firebase#104]
Once logged into via Google Login, calling ```firebase.logout()``` does not permit the user to login with a **different account**. Is there some way to clear the "cache" and change this behavior?

**Comment by EddyVerbruggen** [comment]
There's a `disconnect` feature in the SDK we're not currently using, but first I'd like to reproduce this issue.. I've tested both iOS and Android: log on via Google first, log out, then log in via email-password: works fine. Can you elaborate on your scenario please?

**Comment by calebeaires** [comment]
I was trying something like this:

1. Login with Google (there is more then one accounts on pop-up)
2. Logout, becouse I made a mistake. I want to use another Google account
3. Call again the Pop-up with those accounts
4. Choose some other.

👍

**Comment by EddyVerbruggen** [comment]
Ah, so a different auth provider works, but not the same Google account. Perhaps we _do_ need to call `disconnect` after `logout` then :)

**Comment by EddyVerbruggen** [comment]
For the time being I'm now always disconnecting Google auth users upon `logout`. I can imagine this may be problematic for edge cases so I'll cope with that in case it arises.

In order to get this change install the plugin from github (instead of npm) so you'll get 3.5.2-dev. No code changes required on your end.
