### ISSUE TITLE
App not starting 

### ISSUE THREAD

**Issue by oronoa** [EddyVerbruggen/nativescript-plugin-firebase#1092]
have this repo which was working correctly a few days ago

https://github.com/oronoa/starter_ns

cloned it again and it's not working . getting 'app has stopped' with nothing much in the console log
I did try to delete the platforms dir etc. 
can't get it to work again. what am I doing wrong ??

**Comment by EddyVerbruggen** [comment]
Dunno, but are you sure you need [both Firestore and Realtime DB](https://github.com/oronoa/starter_ns/blob/14c0665a1c2deaf8fc1d8df1205f8a92a982f037/firebase.nativescript.json#L5-L6)? And [these are mutually exclusive](https://github.com/oronoa/starter_ns/blob/14c0665a1c2deaf8fc1d8df1205f8a92a982f037/firebase.nativescript.json#L11-L12).

Furthermore, almost all your dependencies pin to the [major version](https://github.com/oronoa/starter_ns/blob/14c0665a1c2deaf8fc1d8df1205f8a92a982f037/package.json#L17), that means cloning it again later will give you different versions of dependencies.

Since you only give me "it's not working" to work with, I can't provide any more help.

**Comment by oronoa** [comment]
Sorry, forgot to mention I did change the init for the plugin to have only AdMob and messaging which I need. What I'm getting in the emulator is "App has stopped" which not much else in the console I can report about .... any suggestions or something I can do to get more output I will happily run.

**Comment by EddyVerbruggen** [comment]
Check this: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ADMOB.md#android
