### ISSUE TITLE
Version control firebase add-on services configuration?

### ISSUE THREAD

**Issue by acramatte** [EddyVerbruggen/nativescript-plugin-firebase#110]
Hi,

I might be missing something but if I understand correctly, the Android's Gradle file and iOS' Podfile are created and configured during the npm postinstall step.

I find this a bit annoying for the two following reasons:
1. Everyone in the team who installs the project will be prompted for configuring the firebase plugin.
2. A CI build would also be prompted.

Wouldn't there be a way to have a configuration file that could be added to a version control system and the npm postinstall script would first try to read that config file and do the prompting only if it does not already exist ?

**Comment by EddyVerbruggen** [comment]
Sounds useful.. perhaps we can copy it to App_Resources and use that if it exists. BUT what if the install script changes? Then we need to detect that and rerun it (and write it to App_Resources again).

I'm sure that can be automated but let's first discuss this a little. Pinging @sean-perkins since he's the hero that added the script.

**Comment by EddyVerbruggen** [comment]
Automated this in 3.8.0.
