### ISSUE TITLE
Fatal error using MLKitBarcodeScanner

### ISSUE THREAD

**Issue by nicolocaruso85** [EddyVerbruggen/nativescript-plugin-firebase#1153]
Using the component MLKitBarcodeScanner, if the use don't allow access to the camera, app crash with error "Cannot use Back Camera"

**Comment by EddyVerbruggen** [comment]
Is this on iOS and/or Android?

**Comment by nicolocaruso85** [comment]
Only on iOS

**Comment by Dawqss** [comment]
Error log, it occurs when camera access is unavailable

`JavaScript error:
file:///app/tns_modules/nativescript-plugin-firebase/mlkit/mlkit-cameraview.js:50:81: JS ERROR NSErrorWrapper: Cannot use Back Camera
Task <7258805C-B218-4F93-A4A7-B3EE54CEFAB3>.<25> received response, status 201 content K
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   start@file:///app/tns_modules/tns-core-modules/application/application.js:273:26
2   run@file:///app/tns_modules/tns-core-modules/application/application.js:301:10
3   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:185:26
4   bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:103:38
5   bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:87:26
6   anonymous@file:///app/main.js:8:57
7   evaluate@[native code]
8   moduleEvaluation@:1:11
9   promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: NSErrorWrapper: Cannot use Back Camera
at
1   deviceInputWithDeviceError@file:///app/tns_modules/nativescript-plugin-firebase/mlkit/mlkit-cameraview.js:50:81
2   initView@file:///app/tns_modules/nativescript-plugin-firebase/mlkit/mlkit-cameraview.js:50:81
3   createNativeView@file:///app/tns_modules/nativescript-plugin-firebase/mlkit/mlkit-cameraview.js:25:26
4   _setupUI@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:491:47
5   @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:533:27
6   eachChildView@file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:34
7   eachChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:868:27
8   _setupUI@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:532:23
9   @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:533:27
10  eachChildView@file:<\M-b\M^@\M-&>
Task <7258805C-B218-4F93-A4A7-B3EE54CEFAB3>.<25> response ended`

**Comment by EddyVerbruggen** [comment]
Hi, I've wrapped that logic in a try-catch, and the problem is gone. Available real soon in 8.0.0.

**Comment by EddyVerbruggen** [comment]
Just confirmed, this did not happen on Android.
