### ISSUE TITLE
Creating User with Custom Uid

### ISSUE THREAD

**Issue by sarvagayatri** [EddyVerbruggen/nativescript-plugin-firebase#1344]
Can we create user with Custom Uid given which is like 
```
   firebase.createUser({
            uid: uid,
            email: email,
            password: password,
        });
```
as like we do in Admin firebase.
thanks

**Comment by EddyVerbruggen** [comment]
That's a good question. Can you check the native Firebase docs to see if that's possible?

**Comment by kranthi-kiki** [comment]
Yes we can Create User with Custom Uid in Native FireBase.

[](https://firebase.google.com/docs/auth/admin/manage-users#create_a_user)

By default, Firebase Authentication will generate a random uid for the new user. If you instead want to specify your own uid for the new user, you can include it argument passed to the user creation method:


`admin.auth().createUser({
  uid: 'some-uid',
  email: 'user@example.com',
  phoneNumber: '+11234567890'
})
  .then(function(userRecord) {
    // See the UserRecord reference doc for the contents of userRecord.
    console.log('Successfully created new user:', userRecord.uid);
  })
  .catch(function(error) {
    console.log('Error creating new user:', error);
  });`

**Comment by EddyVerbruggen** [comment]
@kranthi-kiki Perfect, then I'd love to have that added!

**Comment by sarvagayatri** [comment]
@EddyVerbruggen thx. We are stuck for the same feature. can you please update the plugin at the earliest. 
thanks.

**Comment by EddyVerbruggen** [comment]
@kranthi-kiki I was about to implement it, but what you've linked to is the Admin API (for Node), so that's not relevant for us. What you need to look at is the [Web API](https://firebase.google.com/docs/auth/web/manage-users) which is usually mimicked by the [iOS](https://firebase.google.com/docs/auth/ios/manage-users) and [Android](https://firebase.google.com/docs/auth/android/manage-users) API's. Unfortunately, neither of those 3 seem to support passing in an `id` param. So your best next action would be opening a feature request with Firebase.
