### ISSUE TITLE
Feature/Question: Is it possible to have more control over push notifications prompt

### ISSUE THREAD

**Issue by cmermingas** [EddyVerbruggen/nativescript-plugin-firebase#165]
I chose the messaging feature when I installed this plugin and when I run the app for the first time, it asks if want to allow push notifications. I think this is done in firebase.init()

I would prefer to show this prompt as part of an onboarding process or just when my users are going to use a feature that requires notifications for the first time.

Is it possible to control when this prompt happens? If not, maybe a feature to consider?

Thanks a lot!

**Comment by EddyVerbruggen** [comment]
I certainly agree. It's the line containing `registerForRemoteNotifications` that's causing this prompt.

**Comment by EddyVerbruggen** [comment]
I've just pushed quite a complex change to this GitHub repo that allows you to control when the prompt is shown.

Check [this updated chapter](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#handling-a-notification).

I'm not pushing to npm right away because I'd like this to be tested a bit first.
