### ISSUE TITLE
Title & Body missing from message object when received in background mode

### ISSUE THREAD

**Issue by thomasmoon** [EddyVerbruggen/nativescript-plugin-firebase#181]
It seems that on Android at least the properties title and body of the message are unset when it's received in the background, even though custom data is available. 

This could be worked around by adding the message text to another custom field, but surely one would expect to be able to read the message text from the same properties as they would when the message is received with the app in the foreground?

**Comment by simonettoa** [comment]
Hi @thomasmoon, I have the same issue. In iOS it works both foreground and background, in android (real or emulator doesn't matter) foreground it works but not in background. How did you solve even using a different key/value pair? I mean, I set as the example of the MESSAGING.md file but is referencing the firebase.Message interface so for example the code below:

`console.log(`Value of 'foo': ${message.data.foo}`);`

Is getting me error because 'data' is not part of the interface.
Thanks in advance.

**Comment by thomasmoon** [comment]
Hi @simonettoa,

the properties in the data "payload" should actually available on the message itself, ie. message.foo

**Comment by simonettoa** [comment]
Thanks @thomasmoon, if someone will be in the same situation here below how I've resolved. I've put any in the declaration of the message parameter to avoid error in compilation (it was automatically getting firebase.Message as interface)

`onMessageReceivedCallback: function(message: any) {`

and call back the payload part as below

`if(message.foo != undefined){
        console.log("********** NOTIFICATION RECEIVED! foo --> " +  message.foo);
 }`

It's an error to call 'message.data.foo', just call message.foo that is part of data. (see the MESSAGING.md at the end of the page to test from the command line).

**Comment by EddyVerbruggen** [comment]
@thomasmoon AFAIK on Android in the background those properties are not received by the app. Not much I can do about that, but you could add anything you need to `data`.
