### ISSUE TITLE
facing issue while login with facebook :prefilling my firebase account details in facebook popup

### ISSUE THREAD

**Issue by LakshmiEvana** [EddyVerbruggen/nativescript-plugin-firebase#227]
By clicking login with facebook,my firebase details are taken as credentials and showing the scren below
![image](https://cloud.githubusercontent.com/assets/17317992/20590287/37f2e74c-b248-11e6-8f36-566e9dc50198.png)
  

and in my console showing as below:
![image](https://cloud.githubusercontent.com/assets/17317992/20590330/7aba2e28-b248-11e6-83b6-2336ab1b42c3.png)

**Comment by EddyVerbruggen** [comment]
Not sure what's wrong here.. can you elaborate?

**Comment by LakshmiEvana** [comment]
We provided facebook login for our app
when we logout of our app using firebase.logout(),its logging out  of the app
but when i click the facebook login button again,its logging in again with the previous credentials that were recently loggedout.
so,i want to logout from the facebook also when i click logout from my app,which should ask login credentials again when i click login with facebook.
How to achieve this?

**Comment by EddyVerbruggen** [comment]
I'm not sure. With Google we're disconnecting the Google account as well, but a quick search seems to reveal we'd need a bit of the Facebook SDK for this. Best to ask the Firebase folks (on StackOverflow perhaps).

**Comment by EddyVerbruggen** [comment]
Done some more research:
- Android: we can fully logout the user like we do with Google on Android.
- iOS: although I've added code to fully clear the Facebook credentials on iOS as well, it seems a common problem that can't be fixed by code: the user needs to remove your app from their Facebook account for them being able to log on with a different account. Perhaps this issue will be fixed by Facebook in the future, in that case the code of this plugin is prepared accordingly.

At least Android will behave like you described (and how Google behaves) in version 4.0.0 of this plugin.
