### ISSUE TITLE
iOS Image Upload Type in Firebase

### ISSUE THREAD

**Issue by ls-spavel** [EddyVerbruggen/nativescript-plugin-firebase#236]
Hello @EddyVerbruggen,

I am experiencing an issue with the file type in Firebase when I upload a photo the user takes. The uploaded file type is always `application/octet-stream`. The file type is `image/png` on android which is what I expect. 

I'm using the [Nativescript-Camera](https://github.com/NativeScript/nativescript-camera) plugin to take a photo, and then save it to the local file system using `ImageSource` with the following code:

```ts
takePicture(pictureOptions).then(
    (picture: imageAsset.ImageAsset) => {
        this.imageSource = new ImageSource();
        this.imageSource.fromAsset(picture).then(
            (imageSource) => {
                if (imageSource) {
                    var fileLocation = fs.path.normalize(this.currentAppPhotoFiles + fileName);
                    imageSource.saveToFile(fileLocation, ImageFormat.png);
                }
            },
            (err) => {
                console.error(err);
            }
        );
    },
    (err) => {
        console.error(err);
    }
);
```

Once the file is saved locally I'm using the following code to do the upload:

```ts
    public uploadFile(file: fs.File, fileName: string, callback: (status) => void = null): Promise<firebase.UploadFileResult> {
        return firebase.uploadFile({
            remoteFullPath: this.basePath + fileName,
            localFile: file,
            onProgress: (status) => callback(status)
        });
    }
```

Any idea why the uploaded type on android is correct but not on iOS?

**Comment by EddyVerbruggen** [comment]
Hi, interesting case, and luckily I can explain why this happens.

On Android we're using a method that allows Firebase to infer the mimetype from its filename, but on iOS we're uploading a data stream (instead of a file) so Firebase is not able to infer the type.

To keep things simple I'd rather have Firebase infer the type than having the developer pass it in (although that would be a nice bonus feature), so I'm going to see if I can refactor the iOS code a bit.

**Comment by EddyVerbruggen** [comment]
Should be OK with version 3.9.0 (release likely tomorrow)
