### ISSUE TITLE
Value Event Listener Is Not Working

### ISSUE THREAD

**Issue by putraxor** [EddyVerbruggen/nativescript-plugin-firebase#238]
Hi, it seems addValueEventListener is not working by now. I've changed values in '/movies' path but it didn't trigger the value event listener. This is my code:
```
global.firebase.addValueEventListener(function (result) {
        var values = result.value;
        var movies = [];
        Object.keys(values).forEach(function (item) {
            movies.push(values[item]);
        });
        console.log(JSON.stringify(values))
        model.set("movies", movies);
    }, "/movies");
```
**I'm sorry, for my case it because the connection lost once. but when it come back online may be the connection is not reconnecting.**

**Comment by ullalaaron** [comment]
I think the path should be "movies/" not "/movies"                                                                                                                                                                                                                                                                                                                                        Invio eseguito dallo smartphone BlackBerry 10.                                                                                                                                                                                                                Da: Ardiansyah PutraInviato: sabato 10 dicembre 2016 04:28A: EddyVerbruggen/nativescript-plugin-firebaseRispondi a: EddyVerbruggen/nativescript-plugin-firebaseOggetto: [EddyVerbruggen/nativescript-plugin-firebase] Value Event Listener Is Not Working (#238)Hi, it seems addValueEventListener is not working by now. I've changed values in '/movies' path but it didn't trigger the value event listener. This is my code:
global.firebase.addValueEventListener(function (result) {
        var values = result.value;
        var movies = [];
        Object.keys(values).forEach(function (item) {
            movies.push(values[item]);
        });
        console.log(JSON.stringify(values))
        model.set("movies", movies);
    }, "/movies");


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/EddyVerbruggen/nativescript-plugin-firebase","title":"EddyVerbruggen/nativescript-plugin-firebase","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/EddyVerbruggen/nativescript-plugin-firebase"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Value Event Listener Is Not Working (#238)"}],"action":{"name":"View Issue","url":"https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/238"}}}
