### ISSUE TITLE
Feature Request: Support crash log API

### ISSUE THREAD

**Issue by toddanglin** [EddyVerbruggen/nativescript-plugin-firebase#307]
I know the docs currently state that the Firebase Crash API is not fully supported, but I wanted to add a vote of interest to see this support added.

Specifically, I'd like to be able to use Firebase for a custom `TraceWriter` so I can log production error messages to Firebase. I started to go down the path of doing this with Firebase Analytics, but it seems it would be more "correct" to use the Crash API for logging this kind of information.

Ideally, the common API for iOS/Android would look something like this:

`firebase.log("Message to log to Crash API goes here");`

Any idea what it might require to enable this in the plugin?

**Comment by EddyVerbruggen** [comment]
Thanks for the suggestion! I'll take a look soon. In the past manually logging was crashy but that's quite a few SDK releases ago so things may currently behave well.

**Comment by toddanglin** [comment]
Taking a closer look at the Firebase API, it seems this would only be possible to support on Android today. The Firebase iOS SDK does not yet seem to support arbitrary logging. You can only create log messages that will be sent along when the next actual crash occurs.

I also noticed `FIRCrashLog` does not show-up in the NativeScript `global` namespace even with the appropriate `Firebase/Crash` pod loaded. Not sure why.

In either case, seems I'll have to look for a different solution for now. What are people using today capture/log production app exceptions?

**Comment by jlooper** [comment]
How about Crashlytics? They were a Twitter subsidiary but not sure if spun off recently with a Fabric. I used Flurry in the past as well.

Best,
J

**Comment by EddyVerbruggen** [comment]
Hey Todd, I noticed the same when working on this for iOS today - at runtime `FIRCrashLog` isn't available either. Most likely because of the way that Pod exposes its functions. Smells like something that needs to be reported to {N}.

I've now 'silently' added `sendCrashLog` to the plugin (see the [TS definition file](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/b8d9d206165df02d2cbed865247684887c12a016/firebase.d.ts#L675)), but as it only works on Android I won't recommend using it. Also because it doesn't seem to fit your usecase anyway.

I'd recommend just using the database functions to add logging; create a /log branch in your DB and structure it any way you like. The good thing about that approach is it's actually realtime and offline available as well.
