### ISSUE TITLE
Support The New Firebase.

### ISSUE THREAD

**Issue by James-Parsons** [EddyVerbruggen/nativescript-plugin-firebase#34]
As many may know, Google just revamped Firebase to include a lot of new features, and the old Firebase will be deprecated. Any chances that this can be updated to match the new Firebase?

**Comment by EddyVerbruggen** [comment]
Yep, BUT I'd really love to have some feedback on what would have priority as it's impossible to do everything at once. So if you have a preference of what exactly you'd like to see landing first let me know!

**Comment by James-Parsons** [comment]
Well, I'd say the Realtime Database and Auth are the two most important features for me.If you need help trying to implement any features, I could probably find time to fork and do a PR.

**Comment by ullalaaron** [comment]
Yes social login wit facebook and google would would something greatly appreciated!

**Comment by nikolal** [comment]
+1 for authentication. Real time database services and authentication should be a priority imo.

**Comment by EddyVerbruggen** [comment]
@James-Parsons That's very nice of you! Let me try to upgrade what we have now first and once that's done anyone can take a stab at adding more awesome features. Hope to pull it off real soon!

**Comment by ullalaaron** [comment]
@EddyVerbruggen that's great news! Thank you for your time and efforts, I believe that this plugin will draw many more people to the {N} community!

**Comment by EddyVerbruggen** [comment]
Hey folks,

I've just created [a new branch](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/tree/firebase-google) which I'd love you to test. It's the latest 🔥 Firebase bits!

The API is almost 100% compatible with the current master branch, so you should be able to just drop it in to any current project. The difference is in the `init()` function: you no longer pass in the firebase URL, but instead (since that's no longer the way to do things according to Google), you download confirguration files which you need to include in your NativeScript project. Nothing to worry about, just don't forget it, details are in the readme.

Once this is tested and merged we can look at adding more features.

**Comment by Moncef12** [comment]
@EddyVerbruggen 

Is it possible to use the full features without this plugin ? (untill this is ready I guess ...)

**Comment by EddyVerbruggen** [comment]
@Moncef12 Of course, you can drop in the firebase SDK in your {N} app yourself. But if you do that you might as well consider forking this plugin (the new branch) and send a PR so others can benefit as well :)

**Comment by nikolal** [comment]
@EddyVerbruggen I tested new version inside my app and everything works as expected. I am using database part of the plugin and email/password auth. Haven't tested social auth.

**Comment by Moncef12** [comment]
Thanks @EddyVerbruggen,

I will see what I can do, for now I'm just starting with android for mobile (I'm using {N} because of code sharing between android app and a web app).

Have a nice day !

**Comment by EddyVerbruggen** [comment]
Thanks for testing @nikolal!

I just pushed 3.0.0 with the latest SDK to npm, so we're now up to date and can start thinking about adding more features, woohoo!
