### ISSUE TITLE
access via AppBuilder IDE 

### ISSUE THREAD

**Issue by mkoepp** [EddyVerbruggen/nativescript-plugin-firebase#4]
After adding this plugin to a new nativescript appbuilder project via properties -> dependencies -> install from plugins marketplace I get an error when trying to require.

var firebase = require("nativescript-plugin-firebase");

Error: Module "nativescript-plugin-firebase" not found
File: "/data/data/com.telerik.NativeScript/files/app/
components/homeView/homeView.js

**Comment by EddyVerbruggen** [comment]
I'm experiencing an issue with AppBuilder as well, but the error is somewhat different: `"Cannot build project because module nativescript-plugin-firebase contains insecure code. Remove the module and try again"`

That's similar to [this issue](https://github.com/NathanaelA/nativescript-sqlite/issues/4) for which Telerik made a platform fix - @teobugslayer, perhaps you can take a look at this plugin as well?

**Comment by adrilort** [comment]
I'm also experiencing a similar issue. I was following the Firebase branch in the Groceries app sample https://github.com/NativeScript/sample-Groceries/tree/firebase.
When I import the nativescript-plugin-firebase, from the plugins marketplace, the app builds fine, but the companion app crashes with the following error:
"Error: Failed to find module 'nativescript-plugin-firebase' relative to 'file:///app/shared/view-models/user-view-model.js'. Computed path: 'app/tns_modules/nativescript-plugin-firebase.js'. "

**Comment by EddyVerbruggen** [comment]
@adrilort That's a different error than I had, but it makes me wonder if @mkoepp only had this error when deploying to the companion app. Not sure the companion app supports this usecase anyway.. does it work when deployed to a standalone app?

**Comment by adrilort** [comment]
@EddyVerbruggen due to the proxy at my office, I can't download & install the Android SDK, so I can only test my app now using the companion app, so I don't know if it works as standalone app. 
Not sure if it helps or not, but the "nativescript-social-share" works fine on the companion app, so I thought the Firebase one was going to work, too.

**Comment by EddyVerbruggen** [comment]
Firebase relies on an external native SDK whereas SocialShare doesn't. That indeed is the difference and a case that's not supported by the companion app. It's cool though that it supports calling into arbitrary native code, as long as it's part of standard iOS/Android SDK's/frameworks.

**Comment by adrilort** [comment]
Thanks a lot for that explanation @EddyVerbruggen. I'll try to run it as standalone app when I get home. Hope it works there. I'll say something otherwise :blush:
