### ISSUE TITLE
FCM Not working on iOS and crashing on Android

### ISSUE THREAD

**Issue by d3mac123** [EddyVerbruggen/nativescript-plugin-firebase#423]
I've followed all the steps to configure both platforms to receive FCM. When I send a message from the Firebase Console:
- nothing happens on iOS devices (app being on back or foreground)
- app crashes on Android, showing just a message "Unfortunately, appName has stopped."

I have tried on real devices and emulators but the results are the same.

This is what I get from Android:
`
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to instantiate service org.nativescript.plugins.firebase.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.asouza.ppgFinder-1/base.apk"],nativeLibraryDirectories=[/data/app/com.asouza.ppgFinder-1/lib/x86, /data/app/com.asouza.ppgFinder-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3147)
	at android.app.ActivityThread.-wrap5(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.asouza.ppgFinder-1/base.apk"],nativeLibraryDirectories=[/data/app/com.asouza.ppgFinder-1/lib/x86, /data/app/com.asouza.ppgFinder-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3144)
	... 8 more
	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
		at java.lang.VMClassLoader.findLoadedClass(Native Method)
		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
		... 10 more
	Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.asouza.ppgFinder-1/base.apk"],nativeLibraryDirectories=[/data/app/com.asouza.ppgFinder-1/lib/x86, /data/app/com.asouza.ppgFinder-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
		... 13 more
`

Any ideas? I am running:
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.1.1           │ 3.1.1          │ Up to date  │
│ tns-core-modules │ 3.1.0           │ 3.1.0          │ Up to date  │
│ tns-android      │ 3.1.1           │ 3.1.1          │ Up to date  │
│ tns-ios          │ 3.1.0           │ 3.1.0          │ Up to date 

"nativescript-plugin-firebase": "^4.0.3",

**Comment by EddyVerbruggen** [comment]
Did you run the setup script after installing the plugin?  And have you tried removing and readding the Android platform folder? There's a library missing that should be part of your build..

**Comment by d3mac123** [comment]
Not sure I understood you (sorry). Which setup script are you referring? This one here? 
`cd node_modules/nativescript-plugin-firebase
npm run setup`

If so, yes, I did it.
Also, what do you mean by "removing and readding the Android platform folder"? What's the path for this folder (so I don't delete anything wrong)?

**Comment by EddyVerbruggen** [comment]
From the root of your app: `rm -rf platforms/android`, then `tns run android`.

**Comment by d3mac123** [comment]
Thanks Eddy. It worked on Android.

Any ideas for the iOS part?

Taking advantage (sorry for the "abuse"), any possibilities to have your great mapbox plugin able to addPolyline on iOS? Just missing it to release my app.

**Comment by EddyVerbruggen** [comment]
Thanks - I think I tried adding polylines but wasn't able to get it to work with NativeScript. Perhaps things are better now. There must be an issue on that repo somewhere that you can watch.

Regarding iOS, try the same thing, and if no message is received (even when the app is in the foreground and you console.log it), then try using `curl` to send the notification. That's the only way I've tried and it works every time. An example is in the messaging readme.

**Comment by d3mac123** [comment]
Via `curl` (sending the device token) I can get the message on iOS (but not via Firebase Console). Thanks!

Regarding the Mapbox plugin, I will be praying for your magic touch there when you have time.

Thanks again for your hard work helping the Nativescript community. Without your plugins, I would not be able to develop my app.

**Comment by EddyVerbruggen** [comment]
Thanks @d3mac123, much appreciated!

**Comment by GeetsKrish** [comment]
Hi Eddy,

I'm also facing the same issue while integrating this plugin in Nativescript-Vue Project.
I am using the plugin version 5.2.0

Unable to instantiate service org.nativescript.plugins.firebase.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/org.nativescript.FirebaseApp1-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.FirebaseApp1-1/lib/x86, /vendor/lib, /system/lib]]
System.err: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2746)
System.err: 	at android.app.ActivityThread.access$1800(ActivityThread.java:151)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:135)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5254)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/org.nativescript.FirebaseApp1-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.FirebaseApp1-1/lib/x86, /vendor/lib, /system/lib]]
System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
System.err: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2743)
System.err: 	... 9 more
System.err: 	Suppressed: java.lang.NoClassDefFoundError: org.nativescript.plugins.firebase.MyFirebaseMessagingService
System.err: 		at dalvik.system.DexFile.defineClassNative(Native Method)
System.err: 		at dalvik.system.DexFile.defineClass(DexFile.java:226)
System.err: 		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
System.err: 		at dalvik.system.DexPathList.findClass(DexPathList.java:321)
System.err: 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
System.err: 		... 12 more
System.err: 	Suppressed: java.lang.ClassNotFoundException: org.nativescript.plugins.firebase.MyFirebaseMessagingService
System.err: 		at java.lang.Class.classForName(Native Method)
System.err: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
System.err: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
System.err: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
System.err: 		... 11 more
System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
ActivityManager: Process org.nativescript.FirebaseApp1 (pid 12792) has died

**Comment by shivgolani** [comment]
System.err: java.lang.RuntimeException: Unable to instantiate service org.nativescript.plugins.firebase.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.ngasce.jforce-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ngasce.jforce-1/lib/arm, /data/app/com.ngasce.jforce-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
System.err:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3282)
System.err:     at android.app.ActivityThread.-wrap5(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6316)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.ngasce.jforce-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ngasce.jforce-1/lib/arm, /data/app/com.ngasce.jforce-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3279)
System.err:     ... 8 more
System.err:     Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
System.err:             at java.lang.VMClassLoader.findLoadedClass(Native Method)
System.err:             at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
System.err:             at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
System.err:             ... 10 more
System.err:     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.ngasce.jforce-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ngasce.jforce-1/lib/arm, /data/app/com.ngasce.jforce-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
System.err:             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:             at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err:             at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:             ... 13 more
ActivityManager: Process com.ngasce.jforce (pid 20501) has died
ActivityManager: cleanUpApplicationRecord -- 20501

**Comment by EddyVerbruggen** [comment]
@shivgolani Please do not crosspost - you just created #687!
