### ISSUE TITLE
Android Build: google-services version conflict error

### ISSUE THREAD

**Issue by Spenstar** [EddyVerbruggen/nativescript-plugin-firebase#493]
After following all of the instructions given to set up this plugin for my NativeScript app, everything is working for iOS (strangely enough), but I am unable to get the Android build to work for the life of me.

Error Message:
```console
Execution failed for task ':processF0F1F2F3F4DebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.2.2.
```
I have tried running `$ANDROID_HOME/tools/bin/sdkmanager --update` as mentioned, but still get the error after running `tns platform remove android` and then `tns build android` and `tns run android`

I have also completely removed android-sdk and reinstalled it, but no luck.

Any insights/help with this would be greatly appreciated.

**Comment by Ablankzin** [comment]
I solve this problem changing the app.glade to use the exact google play service to 11.2.2

**Comment by Spenstar** [comment]
@Ablankzin I'm guessing you mean the `app.gradle` in `app/App_Resources/Android/`. I have tried adding:
```gradle
android {  
  // other stuff here

  project.ext {
    googlePlayServicesVersion = "11.2.2"
  }
}
```
to that file, but I still get the same error.

**Comment by Spenstar** [comment]
Well, it looks like the plugins for the project were messing with the Android build. After removing all the tns plugins and then re-installing them, the build went through.

**Comment by surdu** [comment]
I have the same issue.

```
Execution failed for task ':app:processF0F1F2F3F4DebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest versi
on is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.googl
e.android.gms to 10.0.1.
```

I have a couple of plugins that uses google play services, both of them version 10.0.1.

As far as I understand, the problem is that this plugin [uses a newer version](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/src/platforms/android/include.gradle#L27): 11.8.0 .

So, according to the documentation, I've added 

```
project.ext {
    googlePlayServicesVersion = "10.0.1"
  }
```

at the end of `app/App_Resources/Android/app.gradle` in order to try to convince this plugin tu use this version of the google play services, but with no success.

Am I understanding the problem incorrectly ? Or maybe I'm missing something ?
