### ISSUE TITLE
Question: Can we remove google play service as dependency for android?

### ISSUE THREAD

**Issue by shripalsoni04** [EddyVerbruggen/nativescript-plugin-firebase#52]
First of all 👍  for this very useful plugin.

I noticed that, full library of google play service is included as dependency in `platforms/android/include.gradle`file and due to this, the compile time is getting increased of the app and getting error of DexIndexOverflowException. (I know we have solution now of adding `multiDexEnabled true`)

I tried to compile the project after removing `compile "com.google.android.gms:play-services:9.0.0"` from `include.gradle` (after removing android platform and then re-adding android platform), and the firebase functionalities are working without any issue.

So my question is, do we require full library of google play service as dependency in our app and if we require it, can we add only the required google play service api as dependency to reduce compile time?

You can check all the apis of google play service from here: https://developers.google.com/android/guides/setup#add_google_play_services_to_your_project

**Comment by zhengiko** [comment]
original idea! May be **fetch()** and **http.getJSON()** methods will work in this case? https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/42

**Comment by shripalsoni04** [comment]
@zhengiko I don't know whether it is related to this or not, but I tried to copy the code of **fetch()** and **http.getJSON()** mentioned at #42 in my project which doesn't have dependency `com.google.android.gms:play-services:9.0.0` included. Both the code are logging proper JSON data on console.

**Comment by EddyVerbruggen** [comment]
The play services lib is required for reading google-services.json which contains the Firebase configuration. I previously included the entire library (as documented by Firebase), but I found out that we only need the 'core' bit by default as can be seen [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/platforms/android/include.gradle#L21).

Perhaps you were able to compile without it because you didn't remove and re-add the Android platform afterwards?
