### ISSUE TITLE
Support for AdMob

### ISSUE THREAD

**Issue by jlooper** [EddyVerbruggen/nativescript-plugin-firebase#55]
Another opportunity to reduce the amount of plugins installed would be the ability to use Firebase's built-in AdMob integration. Seems like a great opportunity to augment a three-in-one plugin install.

thanks!

**Comment by EddyVerbruggen** [comment]
Hey Jen,

The problem with adding all these additional features is that Firebase requires additional SDK's to be loaded. For AdMob, Facebook (2 even), Google (1 for login, 1 for Push), and so on.

If I'd enable all of those by default your app would:

- Take forever to build
- Be slower because some of those require bootstrapping
- Be much bigger (apk/ipa size)

On top of that builds would occasionally fail because of unresolved dependencies (network hickups, SDK version bumps, etc). And MultiDex would be required as standard for Android.

And some of those SDK's require manual setup because a plugin can't manipulate certain files (specific .plist entries, .gradle files, app.js).

All of that will make this plugin unusable (you've had your own share already).

So what I'm planning is adding these features to the plugin API but if you want to _use_ fi. AdMob then you have to manually edit a few config files. Mostly that means uncommenting a line in a Podfile or .gradle file.

**Comment by jlooper** [comment]
So they would be available in this plugin, but you enable them ad hoc? Sounds good to me.

**Comment by EddyVerbruggen** [comment]
Also see this awesome PR: #101

**Comment by calebeaires** [comment]
I have implemented on Google Service Ads LITE to this project and also installed you **nativescript-admob** without the dependence copile on its include.gradle. Everthing works well.

```
dependencies {
     ...
     compile 'com.google.android.gms:play-services-ads-lite:9.4.0'
 }

```

More about it on Firebase [Google Mobile Ads Lite SDK](https://firebase.google.com/docs/admob/android/lite-sdk)

**Comment by EddyVerbruggen** [comment]
Added in 3.10.0
