### ISSUE TITLE
Firebase Realtime DB and Firestore in the same app

### ISSUE THREAD

**Issue by d3mac123** [EddyVerbruggen/nativescript-plugin-firebase#553]
Hi,

Any chance, in a near future, to be able to use both Realtime DB and Firestore in the same app? According to Google, this is possible: https://firebase.google.com/docs/firestore/firestore-for-rtdb

The reason I am asking is that my current app could benefit from both scenarios (currently it is only working with Realtime DB).

Thanks!

**Comment by EddyVerbruggen** [comment]
I thought I read somewhere that was not possible but you're right they say it is.

Google doesn't really say how to make them cooperate so I guess it "just works". If that's the case then the installer should be a bit different. Now I'm asking: "Are you using Cloud Firestore instead of the Realtime Database engine (y/n)" and enable Firebase when y, but disable when n.

So it needs to be split into 2 questions really:

"Are you using Cloud Firestore (y/n)"
"Are you using Realtime DB (y/n)"

Do those questions make sense you think?

**Comment by EddyVerbruggen** [comment]
I got it working nicely already - will push 5.0.1 later tonight.

**Comment by d3mac123** [comment]
@EddyVerbruggen you are my idol! :)

**Comment by jagabs** [comment]
just curious, can you access rtdb from firestore rules and vice versa. Ex. if your user account is in rtdb then and lets say you wanted to add rules in firestore using the user details. Is it possible?

**Comment by EddyVerbruggen** [comment]
@jagabs I don't think so, but you better ask this on SO anyway.

**Comment by CarbonEdge** [comment]
It's not impossible I'm doing it right now, by mistake and trying to figure out how to stop.....
