### ISSUE TITLE
Date saved to Firestore get retrieved as strings

### ISSUE THREAD

**Issue by shawndewet** [EddyVerbruggen/nativescript-plugin-firebase#604]
I opened [this stackoverflow question](https://stackoverflow.com/questions/48210494), during the course of which I thought/realized the problem might be in this nativescript-plugin?

This is the code that retrieves the data:
`
return query.get()
  .then(querySnapshot => {
    querySnapshot.forEach(rec => {
    let availabilityRec = rec.data();
    console.log("existing availabilityRec() => " + JSON.stringify(availabilityRec));
`

A breakpoint in Chrome DevTools on that console.log() line reveals availabilityRec.theDate property to be a string.
What should I be doing to have this query return theDate property as a Date object?

**Comment by EddyVerbruggen** [comment]
Is this on Android, iOS or both?

While working on the plugin I noticed something similar on Android. The reason is the plugin is using Google's Gson library to serialize Java to JSON and the result is a String.

I could fix that with a Gson Type Adapter, but I may have to resort to manual conversion anyway because the Firestore reference type isn't compatible with Gson.

**Comment by shawndewet** [comment]
Yeah it's on the Android emulator (I don't have a Mac environment so have not taken the time to test if it's a problem there as well).

**Comment by EddyVerbruggen** [comment]
Just checked iOS: it's fine. With 5.1.3 Android will be fine as well.
