### ISSUE TITLE
Phone Auth - VerificationPrompt TextField change KeyboardType possible?

### ISSUE THREAD

**Issue by rafusfx** [EddyVerbruggen/nativescript-plugin-firebase#619]
Hi, I searched everywhere, but couldn't find it.
I'm using phone auth on my app and it works fine, I just need to change the keyboardType of the TextField of the VerificationPrompt to "phone", so that only numbers appear on the keyboard and the user can type the verification code. Is this possible?

Some other questions would be, where can I style the prompt or if I want a page instead of a prompt, where can I change that?
I looked at the node_modules/nativescript-plugin-firebase couldn't find anything where I could change this things. 

Where is the code that manage all this?

Thank you very much.

**Comment by deifos** [comment]
KeyboardType="number" should do.

**Comment by rafusfx** [comment]
Sorry, I think u don't understand my question. The problem is, I can't find the configuration options for the VerificationPrompt, the code file related to it.

**Comment by EddyVerbruggen** [comment]
The problem is that the plugin uses [the NativeScript `prompt` function](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/953d944fb8f7cdfb592f4dfde7bc3a362bfdfc59/src/firebase-common.ts#L113) and that doesn't support this keyboard type. It only supports [`text`, `password` and `email`](https://github.com/NativeScript/NativeScript/blob/c0a7a45ab97b70ff3f580f5a6515b5a466b0f283/tns-core-modules/ui/dialogs/dialogs.d.ts#L9-L24).

So perhaps the best option is creating a PR for NativeScript to add a more relevant keyboard type (like [I did for the `email` type](https://github.com/NativeScript/NativeScript/pull/3905)). That will of course also benefit folks not using this plugin.
