### ISSUE TITLE
[Feature] support separate dev and prod environments

### ISSUE THREAD

**Issue by abhayastudios** [EddyVerbruggen/nativescript-plugin-firebase#836]
Hey Eddy,

A feature that I am more and more in need of, is to have the plugin support separate dev and prod environments to avoid making errors in production. If you think this is a welcome feature, I could try to have a go at it (on best effort basis :p).

I guess this could be achieved by pulling different versions of `GoogleService-Info.plist` & `google-services.json` depending on whether building with or without the `--release` flag. I was thinking to go for the approach to have a `GoogleService-Info-{prod|dev}.plist` & `google-services-{prod|dev}.json` and fallback to default `GoogleService-Info.plist` & `google-services.json` if they are not present.

I see there is the after-prepare hook `firebase-copy-google-services.js` that handles copying the `google-services.json` for Android, which could probably be easily amended. I couldn't quickly find how the `GoogleService-Info.plist` gets pulled (I'm guessing NS does this since it is a plist file?).

What do you think?

P.S.
- if you have any tips to give on how to handle this out the top of your head that would be most welcome :)
- are you aware of any other places in the code that require handling for different environments?

**Comment by EddyVerbruggen** [comment]
Hey man!

Your assumptions are all spot on, including the one about not needing to copy anything for iOS because it's a plist file.

My gut tells me this plugin should not have to tackle this kind of issue as its more of an app-domain problem. That being said, I don't mind if a little code gets added to support it.

And indeed, copying the correct files to the platforms folder should suffice. To make sure you don't interfere with N's build system i think you have to look for /app_resources/ios/GoogleService-Info.plist.prod and GoogleService-Info.plist.dev for iOS and /app_resources/android/google-services.json.prod and google-services.json.dev.. I hope that will fi make sure the plist file is not added to Xcode (because of the extension). Then the hook can simply rename the plist and json files based on the `--release` flag and the current scripts and N's build will do the rest.

**Comment by abhayastudios** [comment]
@EddyVerbruggen ok I'm done pretty much, but during testing I ran into the following issue.

If you use the storage service you need to define the `storageBucket` property in the object that you feed to `firebase.init()`, which is of course different depending on whether we are using the dev/prod version.

Why do we need to define this in `firebase.init()` at all? The definitions of the Plist and JSON already contain the `STORAGE_BUCKET` key and `project_info.storage_bucket` property respectively. Is there are specific version you are not just getting it from those files?

**Comment by EddyVerbruggen** [comment]
Ha, interesting point. The bucket used to be mandatory but looking at the docs this may no longer be the case (so it prolly gets picked up from those config files you mentioned). I'll make it optionally overridable, and you don't need to worry about it for the PR.
