### ISSUE TITLE
TypeError: null is not an object (evaluating 'snapshot.documents') while logging off

### ISSUE THREAD

**Issue by psrcek** [EddyVerbruggen/nativescript-plugin-firebase#876]
```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x112c32749 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x112c4237b NativeScript::FFICallback<NativeScript:bjCBlockCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x113550561 ffi_closure_unix64_inner
4   0x113550ec2 ffi_closure_unix64
5   0x10cebf505 _ZZZ45-[FSTAsyncQueryListener asyncSnapshotHandler]EUb_ENK3$_0clEv
6   0x10cebf49d _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZZ45-[FSTAsyncQueryListener asyncSnapshotHandler]EUb_E3$_0EEEvDpOT_
7   0x10cebf209 _ZNSt3__110__function6__funcIZZ45-[FSTAsyncQueryListener asyncSnapshotHandler]EUb_E3$_0NS_9allocatorIS2_EEFvvEEclEv
8   0x10cecb12b std::__1::function<void ()>:perator()() const
9   0x10ce7d181 firebase::firestore::util::internal:ispatchAsync(NSObject<OS_dispatch_queue>*, std::__1::function<void ()>&&):_0:perator()(void*)const
10  0x10ce7d158 firebase::firestore::util::internal:ispatchAsync(NSObject<OS_dispatch_queue>*, std::__1::function<void ()>&&):_0::__invoke(void*)
11  0x11585d709 _dispatch_client_callout
12  0x115867708 _dispatch_main_queue_callback_4CF
13  0x114dcbc99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
14  0x114d8fea6 __CFRunLoopRun
15  0x114d8f30b CFRunLoopRunSpecific
16  0x1176e8a73 GSEventRunModal
17  0x1103d4057 UIApplicationMain
18  0x113550d1d ffi_call_unix64
19  0x13cd56170
JavaScript stack trace:
1   @file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:2083:37
2   UIApplicationMain@[native code]
3   start@file:///app/tns_modules/tns-core-modules/application/application.js:272:26
4   run@file:///app/tns_modules/tns-core-modules/application/application.js:300:10
5   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:153:26
6   bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:87:38
7   bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:76:26
8   anonymous@file:///app/main.js:10:57
9   evaluate@[native code]
10  moduleEvaluation@[native code]
11  @[native code]
12  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:2083:37: JS ERROR TypeError: null is not an object (evaluating 'snapshot.documents')
```

this error is displayed **ONLY** on iOS (tested on android) in the console upon running firebase.logout() with a button.

**Comment by EddyVerbruggen** [comment]
What do you do on logout to trigger a snapshot update?

**Comment by jmfsilva** [comment]
I was actually going to open an issue related to this snapshot.document.
The error that i'v got is "file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:2145:37: JS ERROR TypeError: null is not an object (evaluating 'snapshot.documents')"

The line number might be different depending on the version of the testings, but on my code this erros is on firebase_common_1.firebase.firestore.onCollectionSnapshot for the firebase ios version.

I applied a local fix to check if it would solve my problem (complete version):
```
firebase_common_1.firebase.firestore.onCollectionSnapshot = function (colRef, callback) {
    var listener = colRef.addSnapshotListener(function (snapshot, error) {
        if (error || !snapshot) {
            return;
        }
        var docSnapshots = [];
        for (var i = 0, l = snapshot.documents.count; i < l; i++) {
            var document_1 = snapshot.documents.objectAtIndex(i);
            docSnapshots.push(new firebase_common_1.DocumentSnapshot(document_1.documentID, true, firebase_common_1.firebase.toJsObject(document_1.data())));
        }
        var snap = new firebase_common_1.QuerySnapshot();
        snap.docSnapshots = docSnapshots;
        callback(snap);
    });
    // There's a bug resulting in this function to be undefined..
    if (listener.remove === undefined) {
        return function () {
            // .. so we're just ignoring anything received from the server (until the callback is set again when 'onSnapshot' is invoked).
            callback = function () {
            };
        };
    }
    else {
        return function () { return listener.remove(); };
    }
};
```
The new code is the if statement:
```
if (error || !snapshot) {
            return;
 }
```
This is pretty much the same fix as you did for the issue #855.

In my case i had both the issue #855 and this issue.

**Comment by EddyVerbruggen** [comment]
@jmfsilva Yes that's what I intend to do for iOS as well, but since I never have these issues in the demo app I'd like to reproduce them. Any idea why logging out triggers the issue?

**Comment by jmfsilva** [comment]
I'm using Nativescript + Angular.
I subscribe on components onInit and unsubsribe onDestroy.

After login the screen that i'm redirected subscribes to a collection.
To logout i need to navigate to another screen that is accessible from the current screen, I also subscribe to a document on this screen.

Navigating to the screen that has the logout does not call de onDestroy method on the previous component, so it does not unsubscribe from it.

When i click logout i do logout from firebase and move back to a screen that is not guarded.
There is no calls to Unsubscribe before the logout method as success.

Navigating will eventually call onDestroy on both componentes because i'm going back to another page router different from those components. But i can only get to that point after if i fix the issue.

At this point i cannot share any code from my use case, because this is code from my final project.
I would have to clean it allot to avoid leaking important information, and i'm in a tight deadline right now.

**Comment by jmfsilva** [comment]
I suspect that i should make sure i did unsubscribe from evertything before i logout, but that would lead to a more centralized way of dealing with subscriptions.
I expected that onDestroy and onInit would resolve this issues...

Another way to check if this is the issue is: use an intermediate component that would make the onDestroy methods to be called by navigating to it, and on the component actually call logout (this would be just a blank component to force correct order of operations).
I would have to test this theory to make sure that this is actually the issue.

**Comment by EddyVerbruggen** [comment]
Unsubscribing is wise in general, but I'll also add guards to the iOS side of the plugin to prevent this error 👍

**Comment by jmfsilva** [comment]
I'm unsubscribing. The issue is the order of operations :). I must fix the order.
